### ISSUE TITLE
Apple icon decodes incorrectly 

### ISSUE THREAD

**Issue by ezhes** [shusain93/HTMLFastParse#4]
https://reddit.com/r/apple/comments/9enmk1/kuo_ipad_pro_switching_to_usbc_cheaper_macbook/e5q7m5k/

**Comment by royj** [comment]
Hi, first of all cool library you made! I've tested this issue on my simulator and I've found that the default font you set (Avenir-Light) doesn't support the Apple icon. See my screenshot where in the top paragraph I use the system font, and in the second paragraph I use Avenir-Light.

![Screenshot](https://i.imgur.com/H2rOJHZ.png)
